=== 444lessio/BeanHub/beanhub/src/main/resources/xml/Machines_status.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="TypeOfSupply">
    <xs:sequence>
      <xs:element name="coffee" type="xs:nonNegativeInteger"/>
      <xs:element name="milk" type="xs:nonNegativeInteger"/>
      <xs:element name="sugar" type="xs:nonNegativeInteger"/>
      <xs:element name="cups" type="xs:nonNegativeInteger"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TypeOfFaults">
    <xs:sequence>
      <xs:element name="fault" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="code" type="xs:string" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TypeOfDistributor">
    <xs:sequence>
      <xs:element name="position" type="xs:string"/>
      <xs:element name="supply" type="TypeOfSupply"/> <xs:element name="faults" type="TypeOfFaults"/>      </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="state" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="active"/>
          <xs:enumeration value="offline"/>
          <xs:enumeration value="maintenance"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:element name="Globalstate">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="distributor" minOccurs="0" maxOccurs="unbounded" type="TypeOfDistributor"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== 444lessio/BeanHub/beanhub/src/main/resources/xml/Machines_state_ex.xml
<?xml version="1.0" encoding="UTF-8"?>
<Globalstate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="Machines_status.xsd">
  
  <distributor id="Online" state="active">
    <position>Building 19, Floor</position>
    <supply>
      <coffee>85</coffee>
      <milk>70</milk>
      <sugar>90</sugar>
      <cups>150</cups>
    </supply>
    <faults>
      </faults>
  </distributor>
  
  <distributor id="Offline" state="maintenance">
    <position>Building 7, Aula 3.1</position>
    <supply>
      <coffee>10</coffee>
      <milk>0</milk>
      <sugar>40</sugar>
      <cups>25</cups>
    </supply>
    <faults>
      <fault code="M-01">Lack of milk</fault>
      <fault code="E-05">Coin block</fault>
    </faults>
  </distributor>
  
  <distributor id="Offline" state="offline">
    <position>Library,  Study Area</position>
    <supply>
      <coffee>0</coffee>
      <milk>0</milk>
      <sugar>0</sugar>
      <cups>0</cups>
    </supply>
    <faults>
      <fault code="P-00">Out of service</fault>
    </faults>
  </distributor>

</Globalstate>
